import Head from "next/head";
import EPISODES_QUERY from "./../src/Graphql/Queries/Episodes.graphql";
import client from "../apollo-client";
import { ApolloQueryResult } from "@apollo/client";
import MainTitle from "../src/components/home/mainTitle";
import Container from "@mui/material/Container";
import { pagination } from "../src/ts/types/info.types";
import { episodeInitialData } from "../src/ts/types/episode.types";
import FavoritesView from "../src/components/home/favoritesView";

export default function Favorites(): JSX.Element {
  return (
    <div className="bg-main bg-cover">
      <Head>
        <title>Episodes - Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen max-w-screen-lg m-auto">
        <Container className="py-32">
          <MainTitle />
          <FavoritesView />
        </Container>
      </main>
    </div>
  );
}
