import Head from "next/head";

import MainTitle from "../src/components/home/mainTitle";
import Container from "@mui/material/Container";

import dynamic from "next/dynamic";

const FavoritesView = dynamic(
  () => import("../src/components/favorites/view/favoritesView"),
  {
    suspense: true,
  }
);

export default function Favorites(): JSX.Element {
  return (
    <div className="bg-main bg-cover">
      <Head>
        <title>Favorites - Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen max-w-screen-lg m-auto">
        <Container className="py-32">
          <MainTitle />
          <FavoritesView />
        </Container>
      </main>
    </div>
  );
}
