import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Box from "@mui/material/Box";
import Container from "@mui/material/Container";
import { useQuery, gql } from "@apollo/client";
import CHARACTERS_QUERY from "./../src/Graphql/Queries/Characters.graphql";
import client from "../apollo-client";
import Typography from "@mui/material/Typography";

import MainTitle from "../src/components/home/mainTitle";

export default function Home() {
  return (
    <div className="bg-main bg-cover">
      <Head>
        <title>Rick and Morty - Characters and Locations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen max-w-screen-lg m-auto">
        <Box className="pt-12">
          <MainTitle />
        </Box>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps(context: any) {
  const characters = await client.query({
    query: CHARACTERS_QUERY,
  });
  console.log(characters.data.characters.results);
  return {
    props: {
      characters: characters,
    },
  };
}
